sudo: required
services:
    - docker

    before_install:
        - docker build -t vikasraj1471/docker-react-app -f Deockerfile.dev .

    script:
        - docker run vikasraj1471/frontend_react-web-app npm run test -- -- coverage