version: '3'
services: 
    react-web-app:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build: 
           context: .
           dockerfile: Dockerfile.dev
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["yarn", "test"]